sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run bpetri/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh 

install:	
  - ./gradlew build
  - ./cagent_builder.sh make_bundles

after_success:
  - git clone https://github.com/bpetri/deployment_test.git $TRAVIS_BUILD_DIR/deployment_test && cd $TRAVIS_BUILD_DIR/deployment_test
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GITHUB_TOKEN:@github.com" > .git/credentials
  - cp $TRAVIS_BUILD_DIR/deploy/*.jar $TRAVIS_BUILD_DIR/org.inaetics.demonstrator.api/generated/*.jar org.inaetics.demonstrator.java_impl/*.jar  $TRAVIS_BUILD_DIR/deployment_test 
  - git add *.jar && git commit -m "build $TRAVIS_COMMIT" && git push -f 

