sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run bpetri/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh 

install:	
  - ./gradlew export
  - ./cagent_builder.sh make_bundles
